using System.ComponentModel;

namespace HavenheimManager.Enums
{
    public enum Class
    {
        [Description("Alchemist")]
        Alchemist,
        [Description("Arcanist")]
        Arcanist,
        [Description("Aegis")]
        Aegis,
        [Description("Barbarian")]
        Barbarian,
        [Description("Bard")]
        Bard,
        [Description("Bloodrager")]
        Bloodrager,
        [Description("Brawler")]
        Brawler,
        [Description("Cavalier")]
        Cavalier,
        [Description("Cleric")]
        Cleric,
        [Description("Cryptic")]
        Cryptic,
        [Description("Dread")]
        Dread,
        [Description("Druid")]
        Druid,
        [Description("Fighter")]
        Fighter,
        [Description("Hunter")]
        Hunter,
        [Description("Inquisitor")]
        Inquisitor,
        [Description("Investigator")]
        Investigator,
        [Description("Kineticist")]
        Kineticist,
        [Description("Magus")]
        Magus,
        [Description("Marksman")]
        Marksman,
        [Description("Medium")]
        Medium,
        [Description("Mesmerist")]
        Mesmerist,
        [Description("Monk")]
        Monk,
        [Description("Ninja")]
        Ninja,
        [Description("Occultist")]
        Occultist,
        [Description("Oracle")]
        Oracle,
        [Description("Paladin")]
        Paladin,
        [Description("Psion")]
        Psion,
        [Description("Psychic")]
        Psychic,
        [Description("Psychic Warrior")]
        PsychicWarrior,
        [Description("Ranger")]
        Ranger,
        [Description("Rogue")]
        Rogue,
        [Description("Samurai")]
        Samurai,
        [Description("Shaman")]
        Shaman,
        [Description("Shifter")]
        Shifter,
        [Description("Skald")]
        Skald,
        [Description("Slayer")]
        Slayer,
        [Description("Sorcerer")]
        Sorcerer,
        [Description("Soul Knife")]
        SoulKnife,
        [Description("Spiritualist")]
        Spiritualist,
        [Description("Summoner")]
        Summoner,
        [Description("Swashbuckler")]
        Swashbuckler,
        [Description("Tactician")]
        Tactician,
        [Description("Warpriest")]
        Warpriest,
        [Description("Wilder")]
        Wilder,
        [Description("Witch")]
        Witch,
        [Description("Wizard")]
        Wizard
    }
}
